# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_sandstorm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='handle',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
