# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_sandstorm', '0002_auto_20160714_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='sandstorm_id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
